# Generated by Django 3.2.11 on 2022-01-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('from_year', models.CharField(max_length=200)),
                ('to_year', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('university_url', models.URLField()),
                ('university_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkedinJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField()),
                ('company_image_url', models.URLField()),
                ('area', models.CharField(max_length=200)),
                ('from_month', models.CharField(max_length=200)),
                ('from_year', models.CharField(max_length=200)),
                ('to_month', models.CharField(max_length=200)),
                ('to_year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedinSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gitId', models.CharField(max_length=30)),
                ('avatarUrl', models.URLField()),
                ('apiUrl', models.URLField()),
                ('htmlUrl', models.URLField()),
                ('reposUrl', models.URLField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_src', models.CharField(max_length=500)),
                ('current_location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('education', models.ManyToManyField(related_name='education', to='scrap.LinkedinEducation')),
                ('jobs', models.ManyToManyField(related_name='jobs', to='scrap.LinkedinJob')),
                ('skills', models.ManyToManyField(related_name='skill', to='scrap.LinkedinSkill')),
            ],
        ),
    ]
