# Generated by Django 3.2.11 on 2022-01-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_linkedineducation_linkedinjob_linkedinprofile_linkedinskill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinjob',
            name='to_month',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinjob',
            name='to_year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
