# Generated by Django 3.2.11 on 2022-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20220115_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='education',
            field=models.ManyToManyField(to='scrap.LinkedinEducation'),
        ),
        migrations.AlterField(
            model_name='linkedinprofile',
            name='jobs',
            field=models.ManyToManyField(to='scrap.LinkedinJob'),
        ),
        migrations.AlterField(
            model_name='linkedinprofile',
            name='skills',
            field=models.ManyToManyField(to='scrap.LinkedinSkill'),
        ),
    ]
