# Generated by Django 3.2.11 on 2022-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_alter_linkedinprofile_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
